export const FETCHED_LAUNCHES = "FETCHED_LAUNCHES";
export const REQUESTED_LAUNCHES = "REQUESTED_LAUNCHES";
export const REQUESTED_LAUNCHES_SUCCEEDED = "REQUESTED_LAUNCHES_SUCCEEDED";
export const REQUESTED_LAUNCHES_FAILED = "REQUESTED_LAUNCHES_FAILED";
